# Generated by Django 5.0.6 on 2025-01-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_alter_verse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={},
        ),
    ]
